// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSTabPath
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSTabPath.a8bf68de-eafb-40c2-bbb2-b8da07d67630";
        public const string Name = "TabPath";
        public const string Description = @"Shows file paths in tab titles.";
        public const string Language = "en-US";
        public const string Version = "1.3.0";
        public const string Author = "Dark Daskin";
        public const string Tags = "";
    }
}
